version: '3'

services:
  mongodb:
    image: 'mongo'
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /data/db
  lupus_server:
    build: 
      dockerfile: Dockerfile
    restart: always
    container_name: server
    image: lupus_server
    ports:
      - "8080:8080"
    environment:
      - DB_ADDRESS="mongodb://mongodb:27017/LupusDB"
    depends_on:
      - mongodb

